### PR TITLE
v0.28: Telemetry updates

### LINKED ISSUE #1693: v0.28: Telemetry updates
This issue groups all v0.28 updates to the telemetry table:

- Add a `facets` telemetry node
- Rename `formatting.matches` to `formatting.show_matches_position`
- Add new `pagination.maxTotalHits` node
- Add new `faceting.max_values_per_facet` node
- Add new `/task`-filtering-related nodes: `per_task_uid`, `filtered_by_index_uid`, `filtered_by_type`, `filtered_by_status`

## References
- `facets` and `formatting.matches`: https://github.com/meilisearch/specifications/pull/135/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4R116-R117
- `pagination` and `faceting`: https://github.com/meilisearch/specifications/pull/157/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4R133-R134
- task filtering: https://github.com/meilisearch/specifications/pull/116/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4R131-R135

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1693

### CODE REVIEW

**Review by guimachiavelli — APPROVED** [review]
LGTM 🧚‍♂️ 

@gmourier, can you confirm these are all the new datapoints?

**Review by curquiza — COMMENTED** [review]
Is this change added in this PR?
https://github.com/meilisearch/meilisearch/issues/2367

**Comment by maryamsulemani97** [comment]
>Is this change added in this PR?
https://github.com/meilisearch/meilisearch/issues/2367

No, @gmourier said we didn't need to

**Review by curquiza — APPROVED** [review]
LGTM then!

**Comment by maryamsulemani97** [comment]
bors merge

**Comment by gmourier** [comment]
Sorry, I'm late to the party but everything seems well! Thanks @maryamsulemani97

**Pull request merged**
