### PR TITLE
Add Bors

### PR DESCRIPTION
**Pull request by curquiza**
In the PR:
- [ ] Add bors file
- [ ] clean CIs: update GHA versions and put jobs triggered by the same event in the same file.

People who can `bors merge`:
- @dichotommy 
- @guimachiavelli
- @tpayet 
- @curquiza (I can't remove myself from the bors settings 😂)

People who can `bors try`: every Meili people.

People who can still merge using the GitHub button: Tommy and all the administrators. This is a setting (on GitHub side) I can change, I can add anyone you want @dichotommy.
However, I don't recommend merging via GitHub since you use Bors 🙂 If a PR merging with bors and you merge manually with GitHub another PR, it will make bors fail.

💡 If you want to check/follow the bors process or update settings, here is the link: https://app.bors.tech/repositories/28374.
Only the Meili team can access it. You can find the link by clinking on the `Bors` badge on the README (added in this PR)

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
@dichotommy, can you try `bors try` and when you approve the PR, `bors merge`

**Comment by curquiza** [comment]
I hope it will work 🤞

**Comment by dichotommy** [comment]
bors try

**Review by dichotommy — APPROVED** [review]

**Comment by dichotommy** [comment]
bors merge

**Comment by dichotommy** [comment]
@curquiza It appears to have worked! Thank you very much for doing this ❤️ 

Would it cause any problems if we renamed `check-links.yml`? Since it now contains both of our checks (links + style).

**Comment by curquiza** [comment]
You can rename it, itr will not cause any issue with bors. Put me as reviewer on the future PR to be sure 🙂

**Pull request merged**
