### PR TITLE
Add java code samples to sdks.json

### PR DESCRIPTION
**Pull request by ansavanix**
I have added the java code samples file to sdks.json.

### CODE REVIEW

**Comment by dichotommy** [comment]
I tried testing this out by running `yarn build` and serving it locally with `http-server`. I don't see any Java samples present in the code tabs, so I think something isn't quite working. The error is presumably caused by something in the `.code-samples.meilisearch.yaml` in the Java repo, which may not have been prepared yet for integration with the docs site.

What do you think @alallema @bidoubiwa ? Are Java code samples ready to be added to the docs site?

Also, the code sample related to Gradle seems to be a troublemaker.

**Comment by alallema** [comment]
I let you know when it's working

**Comment by bidoubiwa** [comment]
@alallema It appears that there is one missing code sample in the `java` file, if the template file is up to date. Could you add [`list_all_indexes_1`](https://github.com/meilisearch/documentation/blob/c1e0d5d0522848f845890ce34888a88a89dbcef0/.code-samples.meilisearch.yaml#L9) in your code-samples file?

**Comment by curquiza** [comment]
@ansavanix it means you have to change the order in the `.vuepress/code-samples/sdks.json` file

**Comment by curquiza** [comment]
> @dichotommy, it's working fine on local now. And we have the arrow 😃 not sure I like it.

Maybe replacing `JavaScript` by `JS`

**Pull request merged**
