### PR TITLE
v0.27: Add Japanese tokenizer

### LINKED ISSUE #1584: v0.27: Add Japanese tokenizer
v0.27 includes a dedicated Japanese tokenizer, which translates to significantly better search in documents containing Japanese content.

## Tasks
- [x] Update "Language" article with a new list item similar to the one we have dedicated to Chinese

## References
- https://github.com/meilisearch/meilisearch/issues/2185
- SME: none

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1584

### CODE REVIEW

**Review by guimachiavelli — APPROVED** [review]
LGTM 🇯🇵

**Review by dichotommy — APPROVED** [review]
🗾

**Comment by maryamsulemani97** [comment]
@guimachiavelli, this is ready to be merged

**Comment by guimachiavelli** [comment]
bors merge

**Pull request merged**
