### PR TITLE
Updating the default max payload size from 10mb to 100mb

### PR DESCRIPTION
**Pull request by sanders41**
References [Issue 1137](https://github.com/meilisearch/MeiliSearch/issues/1137) and [PR 1147](https://github.com/meilisearch/MeiliSearch/pull/1147)

Increasing the default payload size from 10mb to 100mb.

### CODE REVIEW

**Comment by fharper** [comment]
Please don't merge until https://github.com/meilisearch/MeiliSearch/pull/1147 is merge.

**Comment by curquiza** [comment]
@fharper, isn't the docs based on the latest release of MeiliSearch? I thought it was, so it should even wait for the next release of MeiliSearch, not only the merge of the PR.
Sorry if I'm wrong or I miss something.

**Comment by fharper** [comment]
> @fharper, aren't the docs based on the latest release of MeiliSearch? I thought it was, so it should even wait for the next release of MeiliSearch, not only the merge of the PR.
> Sorry if I'm wrong or I miss something.

Will discuss the process further this week, but yes and no. The main branch should be, but we may want to add missing doc or fix the website itself, things that make sense for the actual release.

**Comment by fharper** [comment]
Thanks @sanders41 !

**Pull request merged**
