### PR TITLE
V0.29: telemetry updates

### LINKED ISSUE #1836: v0.29: Telemetry updates
Updates to the [Telemetry table](https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html#exhaustive-list-of-all-collected-data):
1. Add `per_index_uid`
   - Spec: https://github.com/meilisearch/specifications/pull/169
   - Issue on core: https://github.com/meilisearch/meilisearch/issues/2684
   - SME:
2. Add `most_used_word_matching_strategy`
   - Spec: https://github.com/meilisearch/specifications/pull/173
   - Issue on core: https://github.com/meilisearch/meilisearch/issues/2578
   - SME:
3. Update for auto-batching
   - Spec: https://github.com/meilisearch/specifications/pull/162

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1836

### CODE REVIEW

**Review by gmourier — COMMENTED** [review]
Thanks, @maryamsulemani97 

There is also that telemetry changes https://github.com/meilisearch/specifications/pull/174/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4 🤓

**Comment by maryamsulemani97** [comment]
>There is also that telemetry changes https://github.com/meilisearch/specifications/pull/174/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4 🤓

@gmourier, wasn't this [removed from v0.29](https://github.com/meilisearch/meilisearch/issues/2704#issuecomment-1230185768)?

**Comment by gmourier** [comment]
You are right @maryamsulemani97. My bad!

**Review by gmourier — APPROVED** [review]
LGTM!

**Review by guimachiavelli — APPROVED** [review]
🥜

**Comment by guimachiavelli** [comment]
bors merge

**Pull request merged**
