### PR TITLE
v0.27: Update Docker paths

### LINKED ISSUE #1576: v0.27: Update Docker paths
Due to Docker's peculiarities, the current Docker image and instructions can result in users having to balance three different data locations (one for each of database, snapshot, and dumps).

v0.27 alleviates some of the complexity involved with Docker. The most direct effect to users is that the meilisearch binary has been moved from `./meilisearch` to `meilisearch` _in Docker installs_. There is no effect on the location of binaries for other install method.

## Tasks
- [ ] update Docker install instructions on Quick Start so examples point to `meilisearch`, not `./meilisearch`;
- [ ] check for other Docker code samples;
- [ ] if any code samples are found, update paths on those too

## References
- https://github.com/meilisearch/meilisearch/issues/2235
- SME: @curquiza

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1576

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
LGTM

I invoke @irevoire just in case

**Review by irevoire — APPROVED** [review]
lgtm :+1:

**Review by guimachiavelli — APPROVED** [review]

**Comment by maryamsulemani97** [comment]
@guimachiavelli, this is ready to be merged

**Comment by guimachiavelli** [comment]
bors merge

**Pull request merged**
