### PR TITLE
replace `indexation` with `indexing`

### LINKED ISSUE #1812: Replace "indexation" with "indexing"
We should use "indexing" instead of "indexation" in the docs as most dictionaries still list it as a term with a very specific meaning in economy.

[Slack thread](https://meilisearch.slack.com/archives/C010VV3SHQF/p1659009679811079)

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1812

### CODE REVIEW

**Review by dichotommy — CHANGES_REQUESTED** [review]
Any time we update the name of a Markdown file, that changes the URL generated by VuePress. That means we also have to add a redirect from the old URL to the new one.

**Review by dichotommy — DISMISSED** [review]
LGTM 🥳

**Review by dichotommy — APPROVED** [review]
LGTM 🎁

**Comment by maryamsulemani97** [comment]
closing because too many merge conflicts

**Pull request closed without merging**
