### PR TITLE
Add meilisearch-dart to the SDK list

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Review by dichotommy — APPROVED** [review]
It should also be added in the dropdown menu, right?

**Comment by curquiza** [comment]
Oh yes! adding this!

**Comment by curquiza** [comment]
@dichotommy done! 😊

**Review by dichotommy — APPROVED** [review]
Thanks! 🥰

**Comment by dichotommy** [comment]
bors merge

**Pull request merged**
