### PR TITLE
Fix faulty #2680 merge

### PR DESCRIPTION
**Pull request by guimachiavelli**
For some reason #2680 did not reflect my suggestions, despite the user seeming to have accepted them. This PR fixes that by pushing the final text.

### CODE REVIEW

**Comment by curquiza** [comment]
@guimachiavelli 
You can see on the PR no commit has been pushed following your suggestions -> it means the suggestions were not applied

**Review by curquiza — APPROVED** [review]
tutto bene

**Comment by guimachiavelli** [comment]
huh, you're right. I guess I just assumed the contributor had accepted my suggestions because they had marked my suggestions as resolved without any comment?

**Comment by curquiza** [comment]
> huh, you're right. I guess I just assumed the contributor had accepted my suggestions because they had marked my suggestions as resolved without any comment?

Most of the contributors don't know how to use commit suggestions. I think they thought the suggestions would be applied if they click on "Resolve conversation"
When you do commit suggestions like this, don't wait for their approval -> you are the maintainer, you can apply them directly and then, merge the PR

**Pull request merged**
