### PR TITLE
Add Slack link to `updating.md`

### PR DESCRIPTION
**Pull request by maryamsulemani97**
Add Slack link to warning

### CODE REVIEW

**Comment by dichotommy** [comment]
Does this link work for you? When I try it says that the invitation is no longer active.

**Comment by maryamsulemani97** [comment]
>Does this link work for you?

Yes

**Review by dichotommy — APPROVED** [review]
Approved. Something to be mindful of: https://github.com/meilisearch/devrel/issues/436

**Comment by maryamsulemani97** [comment]
bors merge

**Pull request merged**
