### PR TITLE
Move faq

### PR DESCRIPTION
**Pull request by matboivin**
Closes: #218
Closes: #227

I had to rename `faq.md` into `README.md` (path : `faq/README.md`).

### CODE REVIEW

**Comment by curquiza** [comment]
Hello!
I would like to be requested as reviewer when it's finished 🙂 About the scraper...

**Comment by matboivin** [comment]
Note to self: don't forget to update the link to FAQ in [MeiliSearch readme](https://github.com/meilisearch/MeiliSearch).

**Comment by curquiza** [comment]
And everywhere in the SDK README 😱

**Comment by bidoubiwa** [comment]
Merged into /matboivin/meilisearch-js/faq-toc #321

**Pull request closed without merging**
