### PR TITLE
Add code samples for sorting/filtering nested fields

### LINKED ISSUE #2035: Include examples for filtering and sorting on a nested field
Hello!

I've been receiving questions about how to sort and filter on nested arrays or objects. I understand there is a general explanation about nested objects [here](https://docs.meilisearch.com/learn/advanced/datatypes.html#objects), but could we please include an example in the filtering and sorting section to make it more obvious and simple for Meilisearch newbies

Thanks

### PR DESCRIPTION
**Pull request by guimachiavelli**
Closes #2035

Code samples are currently in code blocks to **_ease_** reviewing, but will be moved to `.code-samples.meilisearch.yaml` and `sample-template.yaml` after approval.

### CODE REVIEW

**Review by maryamsulemani97 — COMMENTED** [review]
Wouldn't it be better to have this in the filtering and sorting guides instead? 🤔

**Review by maryamsulemani97 — DISMISSED** [review]
🍰

**Review by oluademola — APPROVED** [review]
LGTM! Thanks again @guimachiavelli 🎉

**Comment by maryamsulemani97** [comment]
bors merge

**Review by maryamsulemani97 — CHANGES_REQUESTED** [review]
You need to add the code samples to `.code-samples.meilisearch.yaml` and `sample-template.yaml` 👀

**Review by maryamsulemani97 — APPROVED** [review]
🍪 

bors merge

**Pull request merged**
