### PR TITLE
move sub-sections to folders

### PR DESCRIPTION
**Pull request by maryamsulemani97**
1. Creates the following new folders:
- data_backup
- inner_workings
- meilisearch_101
- deployment
- index_settings
2. Updates `sidebarLearn.json`:
- updates slug and source fields

### CODE REVIEW

**Comment by dichotommy** [comment]
Updating the `slug` field may not be necessary anymore. @justkahdri changed the site behavior. I think the rest of the PR is still valid and useful, the additional content organization seems helpful

**Review by dichotommy — CHANGES_REQUESTED** [review]
Can you revert the slug changes but leave everything else the same?

**Review by dichotommy — APPROVED** [review]
LGTM!

**Comment by maryamsulemani97** [comment]
closing for #2273

**Pull request closed without merging**
