### PR TITLE
Documentation Restructure

### LINKED ISSUE #619: Tracker: Documentation Restructure
Working on a big reorganization of our documentation to make it more consistent, browsable, and extendable. This should have a relatively low impact on content.

Detailed proposal: #634 

Work began: 18 January
Estimated completion: 1 February

- [x] Move and rename .md files within the file hierarchy
- [x] Fix navbar and sidebars (update paths in config.js)
- [x] Rewrite main landing page
- [x] Write landing pages for new sections
- [x] Adjust content to better fit within the new structure (may involve creating new pages / splitting some existing pages)
- [ ] Update all links
- [ ] Open PRs to fix links to documentation links in website and other READMEs

### LINKED ISSUE #634: Documentation Restructure Proposal
I would like to propose some changes to how we organize our MeiliSearch documentation.

First, some disclaimers: please note that I am not a UI/UX designer (actually I can’t even draw a straight line) so this proposal merely deals with the organization of content, not presentation. I’m not set on any of the names given in the last section, and I appreciate suggestions. Finally, I want to mention that—just by the nature of this topic—this post will mostly dwell on the negatives of our current documentation, not the many positives of the wonderful content created by @bidoubiwa and others on the team 🙏  I hope it's clear that it is all meant constructively and with an aim to make this resource the best it can be 💪  

### The Problem - Why do we need a new organization for our documentation? 😥 

Right now, our documentation is very effective on a content level. However, the lack of clear architecture (in terms of what type of content goes where) makes it difficult to maintain over time. It also has the side-effect of forcing users to rely on search, since browsing the site is often ineffective.

As a search engine company, this is not a bad problem to have 😉   There’s a reason that our developers seem to be mostly satisfied with our documentation: when you mainly use documentation to solve problems and find API references, navigating by search is ideal. 

However, while the documentation serves us well at this moment, I believe it will become increasingly problematic as it grows in size, and we begin to attract more beginners, hobbyists, and others from outside the open-source community, who expect a more guided approach and a clearer division of information.

**We can break our current problems down into a few parts. Right now:**

1. Most of our feature-oriented reference documentation is lumped together under a single category, “Advanced Guides”, making it difficult to find relevant content by browsing. This includes some information that does not seem particularly advanced (e.g. Installation, Web Interface), as well as all settings.

2. Technical info for some features is spread across multiple pages and sections, which may not be titled clearly, rather than being consolidated in one place (e.g. Searchable Attributes, Dumps).

3. Sections such as Main Concepts, which should focus on broad conceptual understanding, sometimes contain technical information that may or may not be repeated elsewhere (e.g. Ranking Rules).

4. Some API reference pages go beyond a brief description of the task they perform (e.g. Displayed attributes) to the extent that they stop being about the API. This is a problem because when API references give technical info about a feature, it's unclear how that info relates to other locations in the documentation where that feature is described (i.e. is this information unique, or is it repeated elsewhere?)

5. Outside of Getting Started, there is no clear path for beginners. Because there is no clear separation between content for beginners and content for experienced users, pages in the documentation must be written for every audience, instead of targeting a best approach for one specific audience.

I believe we have already received some complaints from experienced users about having to wade through basic search engine concepts and analogies while looking for technical reference info. I suspect that we will experience more of the opposite problem, beginners who are turned off by overly complex concepts mixed in with introductory material, as our software becomes more popular outside of the “open source scene”.

### The Question - What does good documentation organization look like? 🤔 

Django core developer/doc writer [Daniele Procida](https://www.youtube.com/watch?v=t4vKPhjcMZg), among others, breaks software documentation into four categories:

**Tutorials**
* learning-oriented
* rewarding/“fun”
* not necessarily useful in a production context
* _Meili example: Getting Started_

**How-to Guides**
* problem-oriented
* a repeatable “recipe” for achieving a desired result
* useful in a production context
* _Meili example: Setting Up Facets_

**Explanations/Discussions**

* understanding-oriented
* basically, anything that provides a broader context
* more conceptual or theoretical material
* _Meili example:_
    * _Filters or Facets?_
    * _Snapshots vs. Dumps_
    * _almost everything under Main Concepts_

**Technical References**
- information-oriented
- straight-forward, encyclopedia-like entries
- written in consistent technical language
- Consolidate all useful information on a feature
- _Most Meili doc pages currently fall into this category (esp. those under Advanced Guides)_

Currently, MeiliSearch’s documentation **excels at references and how-to guides**, which is why our open-source users appear to be quite satisfied: these categories are the most important for advanced users looking to put our software into production. On the other hand, **we have a lot of room to grow in the areas of tutorials and discussions**, two types of documentation that primarily aid software adoption and learning, not production.

**Let's use these terms to describe two guidelines for our documentation architecture.**
1. Content for beginners (mainly tutorials and simple explanations) should be separate from content for intermediate to experienced users (mainly guides, advanced discussions, and references).
2. Technical references should have their own section—not just API references, but feature references as well. If someone just wants to use our documentation like a manual, they should be able to.

In the future, there are other "best practices" we can codify for our documentation. But for now, these two are the most important for creating a new organizational structure that creates a learning flow and helps users find the content they need.

### My Solution 🚀 

While Daniele’s classification of documentation into four categories is extremely helpful, it’s not a good structure for a documentation site. Four is a bad number: it’s too many categories for a site-wide navbar, and too few categories to really be helpful finding things. Not to mention that the categories have overlap: the difference between guides and tutorials, for example, can be a point of particular confusion for users.

I believe that our eventual goal should be to replace our current three categories (Guides, API References, and Resources) with three new ones based on use-case: **Learn**, **Create**, and **Reference**.

The **Learn** page will contain all information related to learning the software, including tutorials, descriptions of key search concepts, and simple overviews of our key features / selling points.

The **Create** page will contain all the information an intermediate developer needs to put a MeiliSearch site or web app into production: solution-oriented step-by-step guides, plus cool articles, ideas, and comparisons to inspire higher-level projects.

The **Reference** page is pretty self-explanatory! They key thing is that it will contain references for all features, not just the API.

Here's a more hierarchical view:

**Learn**
- Tutorials
    - Getting Started
    - Next Steps
    - etc.
- Key Search Concepts
    - Documents
    - Relevancy
    - etc.
- Feature overview
    - Instant Search (e.g. “MeiliSearch supports Instant Search! Click here to view a guide that will show you how to use it, or click here to view the reference doc.”)
    - Faceting
    - etc.

**Create**
- How To:
    - Implement Instant Search in 5 Minutes
    - Quickly Set Up Attribute Ranking
    - Contribute to MeiliSearch
    - etc.
- Discover
    - Can MeiliSearch be used to help E.R. Doctors quickly diagnose symptoms?
    - Top 5 Sites Using MeiliSearch in Production
    - etc.

**Reference**
- Feature References
    - Indexes
    - Search Parameters
    - etc.
- API References
    - etc.

As far as the labor cost of implementation, these changes would mostly mean moving around files and renaming directories. However, some ambiguous pages (such as those currently under Main Concepts) would require more extensive reworks, or even to be split in two.

Whew, that's it! My hope is that this reorganization will help us have clarity on where every type of content belongs, and allow users to browse the documentation in the way they prefer. Thanks for reading, and please leave your questions, comments, and concerns below ⬇️

### PR DESCRIPTION
**Pull request by react-learner**
Final to do before merging:
- [x] Fix all links (once paths are relatively set in stone)
- [x] Polish all README.md files
- [x] Style check

Future planned improvements (not in this PR):
- Expand "Create" section with "Community Highlights" subsection
- Write new step-by-step guides for **installation** and **updating**
- Split "Field Properties" page in two (unique pages for Searchable Attributes and Displayed Attributes)
- Write learning-oriented articles on Asynchronous APIs, RESTful paradigm, the strengths of prefix search (could go in Core Concepts or Advanced Topics)
- Documentation homepage could be a good place to display patch notes of the most recent release

Would like feedback on:
- Section + subsection names
- Organization of content (does anything feel out of place?)
- Missing content (was any information lost in the reorganization? Answer should be no)
- All landing pages (index.md + all README.md files, accessed by clicking on a section or subsection)

Closes #634 , closes #619

### CODE REVIEW

**Comment by react-learner** [comment]
@curquiza Would you like to contribute an introduction paragraph for sdks.md?

In the preview, you can find this page by going to Learn -> What Is MeiliSearch -> SDKs

**Comment by react-learner** [comment]
Note: Netlify preview appears to be having some problems, consider cloning the branch and doing a yarn dev if you want to poke around.

**Comment by curquiza** [comment]
> @curquiza Would you like to contribute an introduction paragraph for sdks.md?

hum, I like yours in "What is MeiliSearch?" main page ->

```
Our team and community have worked hard to bring MeiliSearch to almost all popular web development languages, frameworks, and deployment options—and new integrations are constantly in development.
```

**Review by fharper — APPROVED** [review]
That is some very good work there! Good job @react-learner 

LGTM

**Comment by curquiza** [comment]
You made an awesome job!! 😁

**Comment by react-learner** [comment]
This did not work, caused the same error as can be seen in the Netlify deploy preview. Strange, as there's no error with local VuePress builds. Must be something on Netlify's end, or else... the scraper? 🤔

**Pull request merged**
