### PR TITLE
Add CODEOWNERS to .code-samples.meilisearch.yaml

### PR DESCRIPTION
**Pull request by brunoocasali**
The idea is to use the [Github's CODEOWNERS feature](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to help us the integrations team, track when the code-samples change.

⚠️ This is not a replacement for the work @maryamsulemani97 graciously does when she creates the issue listing all the changes, this is just a "plus" that will help us automatically review the changes we will implement in the SDKs and also help the docs team to understand if the sample is valid or not.

What happens when a PR with a code-sample change is submitted to the repository? The integration team should be automatically applied as a reviewer.

PS: The whole team should have access to "write" in the repository if you don't feel comfortable opening this permission, we can work differently and just let one of us keep track of it.

### CODE REVIEW

**Review by guimachiavelli — COMMENTED** [review]
Wasn't aware of CODEOWNERS. Interesting functionality, thanks for bringing it up!

I'll check with @dichotommy regarding permissions for the whole team or just a single person. That said, can't it be annoying for your team if everyone gets a notification about every new change to the code samples?

**Comment by bidoubiwa** [comment]
Hey @guimachiavelli, I'm speaking only for me, but on the contrary. Looking at code-sample changes in one PR is easier than looking at them as a whole at the end. We are more bound to see issues when there is less content to review.

Also, for the integration team, being spammed with notifications is our daily life 😂

**Comment by guimachiavelli** [comment]
I stand corrected, @bidoubiwa! 😂

**Review by dichotommy — APPROVED** [review]
🚀

**Comment by maryamsulemani97** [comment]
bors merge

**Pull request merged**
