### PR TITLE
Fix FAQ link in API references homepage

### LINKED ISSUE #642: API FAQ weird 404
On the [API home documentation](https://docs.meilisearch.com/references/), the FAQ link at the top is 404 if you CMD + click to open in a new tab. That is weird because the link is correct, it points to https://docs.meilisearch.com/faq/faq.html but if you CMD + Click (or right click, open in new tab) it open https://docs.meilisearch.com/faq/ . This is 404 at first, but have data when refreshing... I tried on Chrome & Brave, and after clearing my cache. Not sure what is happening here!

image

### PR DESCRIPTION
**Pull request by tpayet**
Trying to fix #642 

I was not able to reproduce the bug locally, so I am submitting a draft PR in order to deploy a test branch on Netlify

### CODE REVIEW

**Comment by tpayet** [comment]
It seems to work, @fharper or @curquiza you can check on the [netlify preview deploy](https://deploy-preview-645--dreamy-wiles-8fd85b.netlify.app) and merge it if appropriate.

**Review by curquiza — CHANGES_REQUESTED** [review]
It works for the FAQ page!! 💪

But there is still the bug for the SSL article permalink I mentioned: https://github.com/meilisearch/documentation/issues/642#issuecomment-745993156

**Comment by tpayet** [comment]
I can't find the reason for the ssl article permalink but it does have the same behavior with how to implement search in react in less than 5 minutes... And guess what, there is also a permalink on this article

I tried to build the link using the permalink directly, but the check link job does not allow this... I am stuck now

**Comment by curquiza** [comment]
I love front-end.
Let's merge at least the fix for the FAQ maybe?

**Review by fharper — APPROVED** [review]
LGTM﻿

**Comment by fharper** [comment]
@curquiza can you create a new issue for the SSL problem please?

**Pull request merged**
