### PR TITLE
replace the deprecated docker-compose

### PR DESCRIPTION
**Pull request by AliakbarGhayoori**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
docker-compose is old and deprecated and now we should use "docker compose" instead.
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [y] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [y] Have you read the contributing guidelines?
- [y] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by guimachiavelli** [comment]
Thanks for this, @AliakbarGhayoori, much appreciated!

Looks good to me!

Just for due diligence: @brunoocasali, can you give your ok as our resident docker person?

**Review by brunoocasali — APPROVED** [review]
Thanks for the contribution @AliakbarGhayoori and thanks for the compliment @guimachiavelli ❤️ 

LGTM!

**Comment by AliakbarGhayoori** [comment]
> Thanks for the contribution @AliakbarGhayoori and thanks for the compliment @guimachiavelli ❤️
> 
> LGTM!

Thanks guys. After this pull request, I also noticed a similar issue in the SQL docs and fixed it in another pull request to keep things consistent: https://github.com/meilisearch/documentation/pull/2836

You all are amazing!

**Comment by guimachiavelli** [comment]
Brilliant, thank you both 🙇 

Merging

**Pull request merged**
