### PR TITLE
documents aligned cropping

### PR DESCRIPTION
**Pull request by MarinPostma**
documents crop alignment as implemented in https://github.com/meilisearch/MeiliSearch/pull/543

### CODE REVIEW

**Comment by Kerollmops** [comment]
We must not merge that, it should only be merged when https://github.com/meilisearch/MeiliSearch/pull/543 is merged and only when a new MeiliSearch release is out!

**Comment by bidoubiwa** [comment]
Could you change de base branch of this PR to the `v0.10` branch?

**Comment by Kerollmops** [comment]
Why v0.10? Nope, we are working to release the v0.9.1 for now, and i think this will be released in 0.9.1.

**Comment by bidoubiwa** [comment]
Ah okey my bad. I will create a v.9.1 branch

**Pull request merged**
