### PR TITLE
Add warning about importing dump versions

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closing #1120

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Thanks for this PR! :)

Some note:
- An example would be welcomed. "using dumps from a new MeiliSearch version to import an older version" is not obvious for everyone, and an example as I wrote in https://github.com/meilisearch/documentation/issues/1120 could help :) You can write a better one of course!
- The title of the PR could be more explicit. What about "Add warning about dumps" or "Add warning about rollback a version using dumps"?
- you should add the issues to the `Linked issues` here, so that GitHub will close it automatically once it's merged!
Capture d’écran 2021-09-21 à 14 18 17
I see you wrote `closing 1120` in the PR description, but if you have had written `closing #1120` it would add the issue automatically to the Linked issues` section

**Comment by maryamsulemani97** [comment]
@curquiza 

- Updated the note to add an example
- Will be careful about naming future PRs
- Linked the issue

**Review by curquiza — CHANGES_REQUESTED** [review]
Awsome @maryamsulemani97! Well done!

I think we had a miss understanding related to the name of the PR. The name of a PR is the title. You can click on `Edit` to change it 🙂

Capture d’écran 2021-09-22 à 15 25 59

**Review by curquiza — APPROVED** [review]
Perfect! :)

**Comment by maryamsulemani97** [comment]
bors merge

**Pull request merged**
