### PR TITLE
Use latest instead of main when requesting the default config file

### PR DESCRIPTION
**Pull request by curquiza**
Latest = the latest stable git tag (so v0.30.5 currently)
main = the branch containing the most recent commit (so more commits than in v0.30.5 currently)

### CODE REVIEW

**Comment by curquiza** [comment]
@meilisearch/engine-team FYI 😇

**Review by guimachiavelli — CHANGES_REQUESTED** [review]
One request and one question:

- Could you also change L#87 of `/learn/cookbooks/running_production.md` so it also uses `latest`?
- I noticed one page uses  `wget` and the other uses `curl` and `>` to download the config file. I'd like to choose one approach and make it consistent for both code samples. Do you have any preferences?

**Comment by curquiza** [comment]
> Could you also change L#87 of /learn/cookbooks/running_production.md so it also uses latest?

✅ 

> I noticed one page uses wget and the other uses curl and > to download the config file. I'd like to choose one approach and make it consistent for both code samples. Do you have any preferences?

I discussed with Kero, and we agreed `curl` is more used and more present by default on the machines than `wget`

**Review by guimachiavelli — APPROVED** [review]
Brilliant, thanks! ❤️

**Comment by guimachiavelli** [comment]
bors merge

**Pull request merged**
