### PR TITLE
move known limitations guide to learn/advanced

### LINKED ISSUE #1376: Move `reference/features/known_limitations` to `learn/advanced/`
As part of our ongoing site restructure, I propose we move `reference/features/known_limitations.md` to `learn/advanced` under the "Inner workings" heading.

### PR DESCRIPTION
**Pull request by guimachiavelli**
Closes #1376

### CODE REVIEW

**Review by dichotommy — APPROVED** [review]
LGTM! 🍪

**Review by dichotommy — APPROVED** [review]
🧙‍♂️

**Comment by guimachiavelli** [comment]
you hear that, bors, old bot? go get them, champ

bors merge

**Comment by guimachiavelli** [comment]
good bors 🍪

**Pull request merged**
