### PR TITLE
Comparison to alternatives Updated

### LINKED ISSUE #2191: Update comparison to alternatives
Update the [Comparison to alternatives](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html) page:

- Elasticsearch's [source code licensing](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html#general-overview) returns "page not found"
- Elasticsearch is described as "not open-source" in the [table](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html#general-overview), but in the conclusion, it says it is and is listed in the[ open source section](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html#elasticsearch)

### PR DESCRIPTION
**Pull request by roy9495**
# Pull Request

## Related issue
Fixes #2191 

## What does this PR do?
- Elasticsearch's source code licensing returns the "page not found" problem mentioned in this issue is already solved.
- Moved elasticsearch from open-source to closed-source section and in the conclusion changed elasticserch's details as a closed-source search engine.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by maryamsulemani97** [comment]
Hey @meilisearch/devrel-team! Could you please review this PR?

**Comment by ferdi05** [comment]
Hi @roy9495 thanks for your contribution. We actually discussed this internally and would like to say Elasticsearch  is `source available`. It can be confusing, but that's our best understanding of the current situation.

**Comment by ferdi05** [comment]
@maryamsulemani97 I made a very few changes to the PR and it should be ok

**Review by maryamsulemani97 — APPROVED** [review]
Thanks for the PR @roy9495!

**Comment by roy9495** [comment]
Thank you

**Pull request merged**
