### PR TITLE
Update storage.md

### PR DESCRIPTION
**Pull request by jellevdvliet**
I assume the virtual memory usage is only 205Mb instead of 205Gb?

### CODE REVIEW

**Comment by guimachiavelli** [comment]
@curquiza and @gmourier, can either of you confirm this is a typo? 205GB does sound…excessive 😅

**Comment by curquiza** [comment]
Checked with @Kerollmops 

This is not a typo: this is the virtual memory and not the real physic memory that is allocated. MeiliSearch could take 205Gb of memory but does not really immediately: your OS will manage the physical memory it really allocates for MeiliSearch on its own.

**Review by curquiza — CHANGES_REQUESTED** [review]
👆

**Comment by jellevdvliet** [comment]
Good to know. I think the docs should be expanded then to explain the 205Gb because it definitely looks like a typo 😅 .

**Pull request closed without merging**
