### PR TITLE
Remove Typesense from comparison

### PR DESCRIPTION
**Pull request by tpayet**
Remove typesense from comparison until we make a proper test of Typesense
Related to [meilisearch/MeiliSearch#1148](https://github.com/meilisearch/MeiliSearch/issues/1148)

### CODE REVIEW

**Review by eskombro — APPROVED** [review]
👍🏽

**Review by curquiza — APPROVED** [review]

**Review by react-learner — COMMENTED** [review]
Perhaps instead of entirely deleting the Typesense section of "A Quick Look at the Search Engine Landscape", we could give a short unoffensive description.

Could be something like this: "Typesense is a simple, lightweight search engine optimized for speed. We have purposefully left it out of our above comparison while we re-evaluate its features and functionality."

**Comment by fharper** [comment]
Let's remove it from now, we need to take the time to have a proper comparaison of their new version!

@react-learner: can we merge this ASAP.

**Comment by react-learner** [comment]
> Let's remove it from now, we need to take the time to have a proper comparaison of their new version!
> 
> @react-learner: can we merge this ASAP.

@fharper Please let me know if you approve my changes. I added a disclaimer at the top of the file and a shortened description of Typesense to explain its absence from our comparison.

**Review by fharper — APPROVED** [review]
LGTM

**Comment by fharper** [comment]
Thanks!

**Pull request merged**
