### PR TITLE
Update top navbar #1447

### LINKED ISSUE #1447: Update top navbar
Some updates to the top navbar of our site:

- [x] Rename top navbar link `Reference` -> `API Reference`
- [x] Add link to blog
- [ ] ~Add link to landing page?~

### PR DESCRIPTION
**Pull request by Rutam21**
# Pull Request

## What does this PR do?
Fixes #1447 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by dichotommy — CHANGES_REQUESTED** [review]
Hey @Rutam21 , thanks for your PR! 😄 

Just one request: could you move the blog link so that it appears after the link to our Slack? It should be the last element in `nav`. This is because we want to keep all navbar links that lead off the site in the same area.

**Comment by Rutam21** [comment]
@dichotommy I have updated the PR. Please review.

**Review by dichotommy — DISMISSED** [review]
LGTM! Thanks @Rutam21 🚀

**Review by dichotommy — APPROVED** [review]
🥇

**Comment by dichotommy** [comment]
bors merge

**Pull request merged**
