### PR TITLE
add an action to update the year automatically

### PR DESCRIPTION
**Pull request by fharper**
trying with a manual workflow for test

### CODE REVIEW

**Comment by fharper** [comment]
Will modify to be automatic on January 1st if this action works well.

**Review by eskombro — APPROVED** [review]
That is an interesting GH action! Seems good! Any reason to prefer triggering it manually than using for example the CRON option?

LGTM 👌🏽

**Comment by fharper** [comment]
Just want to try it first because automating it and adding it to all repos.

**Comment by fharper** [comment]
Unfortunately, it doesn't work with `LICENSE.md`, just `LICENSE` file. I created an issue https://github.com/FantasticFiasco/action-update-license-year/issues/111

**Comment by eskombro** [comment]
Shouldn't we actually call it `LICENSE` instead of `LICENSE.md`?

**Comment by fharper** [comment]
Both are valid. I prefer Markdown so we can use markdown if needed. I also think all files should have an extension, even text based ones. Lastly, it is consistent with our other files like CONTRIBUTING.md.

It's not the end of the world for me, just sharing why I create LICENSE.md when I manually add a license to a repo.

**Comment by eskombro** [comment]
Perfect :)

**Pull request merged**
