### PR TITLE
update settings api

### LINKED ISSUE #1520: Settings API - Feedback
Hi @meilisearch/docs-team!

While writing the [catch-up specification for the Settings API](https://github.com/meilisearch/specifications/pull/123), I took the opportunity to write down some little details I noticed on the documentation that might interest you.

## Reindexing Documents On Settings Change

In the `filterableAttributes` API Reference, it is mentioned that updating the setting will re-index documents but this is not mentioned on other settings API Reference.

Changing any of the following index settings will cause documents to be re-indexed:

- `searchableAttributes`
- `filterableAttributes`
- `sortableAttributes`
- `distinctAttribute`
- `stopWords`

You may want to mention that for consistency.

## Missing Description

Location: https://docs.meilisearch.com/learn/configuration/settings.html#index-settings

`sortableAttributes` seems missing a proper description.

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1520

### CODE REVIEW

**Review by gmourier — APPROVED** [review]
LGTM ✨ Thanks!

**Comment by maryamsulemani97** [comment]
bors merge

**Review by guimachiavelli — APPROVED** [review]
LGTM 🦦

**Comment by maryamsulemani97** [comment]
bors merge

**Pull request merged**
