### PR TITLE
Add synonyms created by the community

### LINKED ISSUE #483: List of synonyms coming along with MeiliSearch
**Is your feature request related to a problem? Please describe.**
No, it's just a feature that could be added to improve the results

**Describe the solution you'd like**
A list of the main synonyms (like written (one, two...) and unwritten (1, 2...) numbers) that come with MeiliSearch by default, improving search results. They can be added and supported by the community, including list with different languages...

**Describe alternatives you've considered**
If the list cannot come by default, it can be hosted on this GitHub repository, so anyone who wants to use these synonyms can clone a copy of the file containing the list

**Additional context**
If someone search by _John Wick: Chapter 2_ or _John Wick: Chapter Two_ the results would be the same without the necessity of the developer create a synonyms list

### PR DESCRIPTION
**Pull request by andresribeiro**
This close #483

### CODE REVIEW

**Comment by fharper** [comment]
Hi @andresribeiro! First, thanks a lot for the PR, I think having a list of synonyms is a great idea and will be useful.

I have a suggestion for you. What if, we create a synonyms repo inside our organization, and you do a PR with your synonyms there instead of linking them on your repositories? Don't get me wrong, we don't want to take the congratulations on your hard work, but it would be easier for us to manager multiple languages, languages you may not care about. I would be sure to put your name and picture in the README, so anyone can see. Would that be a possibility?

**Comment by andresribeiro** [comment]
> Hi @andresribeiro! First, thanks a lot for the PR, I think having a list of synonyms is a great idea and will be useful.
> 
> I have a suggestion for you. What if, we create a synonyms repo inside our organization, and you do a PR with your synonyms there instead of linking them on your repositories? Don't get me wrong, we don't want to take the congratulations on your hard work, but it would be easier for us to manager multiple languages, languages you may not care about. I would be sure to put your name and picture in the README, so anyone can see. Would that be a possibility?

Of course! I did it this way because I thought it would be kind of boring for you to analyze several synonyms in several languages that you may not even speak, but if you prefer it this way, that's fine with me :)

**Comment by fharper** [comment]
Awesome, I'll close this PR, please do one at https://github.com/meilisearch/synonyms

Thanks again, I appreciate your understanding (and yes, analyzing synonyms may not be exciting, but we want to make it easier for our community :D )

**Comment by andresribeiro** [comment]
@fharper I will close the issue related to this PR. How would you like it to be organized in this new repository?

**Comment by fharper** [comment]
Let me write down the README file tomorrow or beginning of next week: I'll add guidelines about the structure of the repo and files.

Thanks again!

**Pull request closed without merging**
