### PR TITLE
docs: uniform log-level style

### PR DESCRIPTION
**Pull request by jeertmans**
# Pull Request

## Related issue
None

## What does this PR do?
Related to PR [#2839](https://github.com/meilisearch/meilisearch/pull/2839) in the main repo, I saw that the documentation seemed to contain typos in the log-levels descriptions.

This fixes them.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by dichotommy — APPROVED** [review]
LGTM 👌🏻

**Comment by dichotommy** [comment]
Thanks for your PR @jeertmans ! 🔥 

bors merge

**Comment by jeertmans** [comment]
@dichotommy thanks for merging! But then "four" also needs to be replaced by "five", as in the other PR our reviewed ;-)

Should I create another PR?

**Comment by jeertmans** [comment]
Additionally, @dichotommy, is it possible to add the `hacktoberfest` label to this repo too?

Seems like the main one is participating in the Hacktoberfest, but not this one ;-)

image

**Pull request merged**
