### PR TITLE
Add "NOT PRODUCTION READY" disclaimer in syncing with meilisync chapters

### PR DESCRIPTION
**Pull request by vaddenz**
# Pull Request

## What does this PR do?

After spending some time engaing with meilisync, it turns out that this project is still in a state of flux, lacking comprehensive testing and readiness for deployment in a live environment which is NOT suitable in the official document. I think it is necessary to address potential issues so that users could pay attention to this and make their own decisions.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by guimachiavelli — APPROVED** [review]
Thanks for the contribution, @vaddenz. 

It looks good and I'm preemptively approving it. I'll leave the final call to @Strift, though.

That said, we've been getting more and more reports from users having problems with meilisync. I'm starting to wonder whether it wouldn't be better to remove this guide, since people shouldn't need to wonder whether a tool featured in our docs is safe to use.

**Review by Strift — APPROVED** [review]
Hi @vaddenz, and thank you for your contribution.

I'm sorry to hear your feedback about Meilisync, and support Gui's opinion here. We might have to reconsider recommending Meilisync altogether in the future.

We opened a discussion on the topic, your feedback is more than welcome: [RFC: database sync tool](https://github.com/orgs/meilisearch/discussions/765)

Thanks,

**Comment by vaddenz** [comment]
Hi guys, thanks for the quick review. I appreciate you and meilisync's authors brilliant hard work and agree that removing it is better.

**Review by Strift — APPROVED** [review]

**Comment by guimachiavelli** [comment]
@vaddenz, if I may ask for another bit of your time: could you describe what issues you had when using meilisync? We're currently collecting feedback from meilisync users, which may help our support team field some of the questions coming in.

**Comment by vaddenz** [comment]
> @vaddenz, if I may ask for another bit of your time: could you describe what issues you had when using meilisync? We're currently collecting feedback from meilisync users, which may help our support team field some of the questions coming in.

Hi @guimachiavelli , here are some issues I've experienced:

1. Usability: Following the project's configuration guide, the project was unable to start and throwed some exceptions. Here is a related issue: https://github.com/long2ice/meilisync/issues/94
2. Reliability: Seems that meilisync was unable to capture some changes made in the DB
3. Poor maintenance

As for the sync tool, I'd suggest that MeiliSearch consider officially integrating some common utilized projects, e.g. Canal, Debezium etc

**Comment by guimachiavelli** [comment]
Brilliant, thanks for the feedback, @vaddenz! I'll pass this along to support and to our product managers, as it will really help them both managing current support requests and solving the issue more definitively in the future!

thanks again!

**Pull request merged**
