### PR TITLE
Add Rust SDK link

### PR DESCRIPTION
**Pull request by arjunyel**

### CODE REVIEW

**Review by eskombro — APPROVED** [review]

**Review by eskombro — CHANGES_REQUESTED** [review]
Rust SDK is still considered a WIP I think, and that's why it hasn't been added to the docs

**Comment by arjunyel** [comment]
I think even if it's WIP it still worth adding to the docs, once they click the link it'll show the status of the SDK

**Comment by bidoubiwa** [comment]
Hey @arjunyel, 
I will merge your PR as soon as I have confirmation from @curquiza. She is on holliday for a few more days.

**Review by tpayet — APPROVED** [review]

**Review by curquiza — APPROVED** [review]
The package is ready to become an official SDK!

**Pull request merged**
