### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by kianmeng**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- Fix spelling errors found via `codespell -S assets -L sade,trough,tha`

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by guimachiavelli — DISMISSED** [review]
Hi there, @kianmeng! Terribly sorry about how long it took me to take a look at your PR. Busy times here with the launch of v1.9.

Thanks for your contribution, it is really much appreciated 🙏

**Comment by guimachiavelli** [comment]
Apologies, @kianmeng, but it seems there are a few conflicts with `main`. Would you be able to fix them locally and update this PR?

If you are not able, that's totally fine. Since I don't have access to your specific branch `kianmeng:fix-spelling-errors`, I will have to open a new PR and close this one. Your changes will still be attributed to your GitHub user.

Thanks again!

**Comment by kianmeng** [comment]
@guimachiavelli Conflict resolved.

**Comment by guimachiavelli** [comment]
Briliant, thank you so much, @kianmeng!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
