### PR TITLE
Add a deployment guide for Sealos

### PR DESCRIPTION
**Pull request by yangchuansheng**
## What does this PR do?
- Add a deployment guide for Sealos

### CODE REVIEW

**Comment by yangchuansheng** [comment]
Preview:

Screenshot 2024-07-02 at 12-11-14 Sealos Cloud

After deployment:

Screenshot 2024-07-02 at 12-12-08 Sealos Cloud

**Comment by guimachiavelli** [comment]
Thanks for submitting this new guide, @yangchuansheng!

@Strift and @CaroFG, the "Guides" section is more your turf than mine, so I'll let you make the final call on whether we want to feature Sealos and feel capable of keeping it up-to-date in the future.

**Comment by Strift** [comment]
你好 @yangchuansheng 👋 

Thank you for contributing to Meilisearch documentation!

Sorry, but we currently don't accept community guides about third-party tooling. I encourage you to write and publish this post on Sealos's documentation, and we will include it in the [awesome meilisearch](https://github.com/meilisearch/awesome-meilisearch) list.

Have a good day,

**Comment by yangchuansheng** [comment]
> 你好 @yangchuansheng 👋
> 
> Thank you for contributing to Meilisearch documentation!
> 
> Sorry, but we currently don't accept community guides about third-party tooling. I encourage you to write and publish this post on Sealos's documentation, and we will include it in the [awesome meilisearch](https://github.com/meilisearch/awesome-meilisearch) list.
> 
> Have a good day,

Thanks, I've published this post on [Sealos's documentation](https://sealos.io/blog/how-to-deploy-and-configure-meilisearch-using-docker). I was wondering if you could include it in the [awesome meilisearch](https://github.com/meilisearch/awesome-meilisearch) list

**Pull request closed without merging**
