### PR TITLE
update code samples

### LINKED ISSUE #1541: Camel case in code-samples name
The following code-sample names contain a mixture of Camel and Snake cases:
`getting_started_update_rankingRules_md: |-`
`getting_started_update_displayedAttributes_md: |-`
`getting_started_update_searchableAttributes_md: |-`
`getting_started_geoRadius_md: |-`
`getting_started_geoPoint_md: |-`

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1541 

- Updates any cameCase code sample names to snake_case
- Removes unused code samples
- Removes `_md` from code sample names

### CODE REVIEW

**Comment by guimachiavelli** [comment]
Will review this later this week, but one important comment: we should not remove the `_md` sample from all code sample names, only from those we're sure do not require the special behaviour triggered by `_md`.

**Comment by maryamsulemani97** [comment]
>Will review this later this week, but one important comment: we should not remove the _md sample from all code sample names, only from those we're sure do not require the special behaviour triggered by _md.

Checked with Charlotte and this code sample was okay without `_md`

**Review by dichotommy — APPROVED** [review]
🎸

**Comment by maryamsulemani97** [comment]
bors merge

**Pull request merged**
