### PR TITLE
[FIX]: Handle broken links checker edge-cases

### PR DESCRIPTION
**Pull request by justkahdri**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by justkahdri** [comment]
I'll run some more tests by Thursday, but in the meantime, the checker found some more broken links that could be useful for you @guimachiavelli

**Comment by justkahdri** [comment]
@guimachiavelli I'm pretty confident it works as it should now. Please let me know if you found any other link that wasn't being reflected on the checker. 

Also LMK if you would want me to update the action messages as we once discussed on our weekly meetings. 🙏🏼

**Comment by guimachiavelli** [comment]
hi, @justkahdri!

Was away yesterday, will look into this later.

FYI, one our devs reported they were scraping the docs and found two other unreported dead links: https://www.meilisearch.com/docs/learn/experimental/learn/configuration/instance_options and https://www.meilisearch.com/docs/learn/advanced/reference/api/facet_search. 

I cannot find these with grep and the like. Looking at the links and how they sort of nest sections that have never been nested (e.g. `reference/api` as a sub dir of `learn/advanced`), I'm thinking these might be due to a missing `/` at the beginning of a link. For example, a link to `learn/configuration/instance_options` instead of `/learn/configuration/instance_options`. What do you think?

**Review by guimachiavelli — DISMISSED** [review]
Seems to be working as expected now.

One comment: unless I'm missing something, `related` is a confusing name for broken links missing a leading `/`. I suggest we change that to `relative`.

**Comment by justkahdri** [comment]
Fixed @guimachiavelli, seems the approve is necessary again

**Review by guimachiavelli — APPROVED** [review]

**Comment by guimachiavelli** [comment]
Approved. May I merge it or should I wait for your signal?

**Comment by justkahdri** [comment]
Ship it! :shipit:

**Pull request merged**
