### PR TITLE
Prepare documentation for v0.21

### PR DESCRIPTION
**Pull request by dichotommy**
# v0.21

This PR will include all changes to the documentation coming in v0.21.

### https://github.com/meilisearch/transplant/issues/85 Changes to Ranking Rules
- [x] Fix in Relevancy
- [x] Fix in Ranking Rules API ref
- [x] PR created: https://github.com/meilisearch/documentation/pull/974
- [x] PR merged

### https://github.com/meilisearch/specifications/pull/34 https://github.com/meilisearch/transplant/issues/180 New telemetry page
- [x] Create new docs page detailing MeiliSearch default telemetry, explanation for why we take this data, and instructions for opting in/out
- [x] PR created https://github.com/meilisearch/documentation/pull/1020
- [x] PR merged

### https://github.com/meilisearch/specifications/blob/main/text/0043-phrase-query.md New feature: Phrase Search
- [x] Add mentions of phrase search in search parameters feature reference, search API reference
- [x] PR created https://github.com/meilisearch/documentation/pull/1021
- [x] PR merged

### https://github.com/meilisearch/transplant/issues/81 https://github.com/meilisearch/transplant/issues/140 Changes to Facets + Filters
- `attributesForFaceting` renamed to `filterableAttributes`
- `facetFilters` parameter no longer exists
- `filters` parameter changed to `filter`, and now works for facets as well but requires fields to be defined in `filterableAttributes`
- `facetsDistribution` no longer returns zero values (see: https://github.com/meilisearch/transplant/issues/234)
- `filter` can use both logical and array syntax
- [x] PR created: https://github.com/meilisearch/documentation/pull/1041
- [x] Create new Filtering and faceted search feature ref
- [x] Remove Filtering feature ref
- [x] Remove Faceted Search feature ref
- [x] Fix in Search Parameters feature ref
- [x] Fix in Settings feature ref
- [x] Fix in attributesForFaceting API ref
- [x] Add redirects from `attributesForFaceting` to `filterableAttributes`
- [x] Add warning: `exhaustiveFacetsCount` is not currently implemented and always returns `false`
- [x] PR merged

### https://github.com/meilisearch/transplant/issues/107 Addition of new update status value `processing`
New full list of update statuses:
> enqueued: the update is enqueued and will start to be processed soon
**> processing: the update is processing.**
> processed: the update is processed and it succeeded.
> failed: A failure occurred during when processing.

- [x] create PR #1046 
- [x] review `learn/advanced/asynchronous_updates.md` (see issue #902)
- [x] update status list on `learn/advanced/asynchronous_updates.md` (see issue #877)
- [x] merge PR

### https://github.com/meilisearch/transplant/issues/217 Reset settings by passing a null value
- [x] create PR #1048
- [x] update note on `reference/api/settings.md`
- [x] merge PR

### https://github.com/meilisearch/transplant/issues/119#issuecomment-867726976 Update Known Limitations
1. Removed max number of indexes;
2. Filterable attributes values are limited to 500 bytes;
3. Total number of documents in a single index is limited to 4 294 967 296.
- [x] PR created  #1053 
- [x] update `reference/features/known_limitations`
- [x] PR merged 

### https://github.com/meilisearch/transplant/issues/20#issuecomment-852195621 Changes to Dumps
- [x] create PR #1054
- [x] reference/features/configuration.md: remove `--dump-batch-size` L#67, L#193, L#200, #L208
- [x] create/how_to/updating: remove `--dump-batch-size` L#241
- [x] reference/api/dump: remove `--dump-batch-size` L#11
- [x] reference/features/dumps: remove `--dump-batch-size` L#31
- [x] add `startedAt` field to `POST` `/dumps` route (`reference/features/dumps`, `create/how_to/updating` (L#220-227), `reference/api/dump` (L#49-54))
- [x] add `startedAt` and `finishedAt` fields to `GET` `/dumps/:uid/status` route (`create/how_to/updating` (L#204-212), `reference/api/dump` (L#25-30))
- [x] add new known limitation to `reference/features/dumps`
- [x] merge PR

- [x] create PR #1055
- [x] Add warning `reference/features/field_properties` (L#48?)
- [x] Add warning `reference/api/searchable_attributes` (L#12?)
- [x] merge PR

### https://github.com/meilisearch/transplant/issues/87 New mini dashboard / web interface #1031
- [x] Replace all screenshots featuring the old web interface with ones featuring the new design

## Configuration options

- [x] create PR #1057

---

- [x] /reference/features/configuration.md: add option description (alphabetic order)
- [x] /reference/features/configuration.md: add defaults to `--env` var (`production` uses INFO) L#107, L#113

- [x] /reference/features/configuration L#68, L#218, L#219, L#226, L#228
- [x] /learn/getting_started/installation L#102
- [x] /reference/features/known_limitations L#15

- [x] notify core team link to no-analytics option changed to https://docs.meilisearch.com/reference/features/configuration.html#disable-analytics
- [x] /reference/features/configuration: remove --no-sentry L#165-174
- [x] /reference/features/configuration: add line explaining sentry is now handled by --no-analytics L#163
- [x] /reference/features/configuration: link to telemetry page L#163

- [x] /learn/core_concepts/documents: remove "must be in bytes" L#161
- [x] /reference/features/configuration: update description clarifying a user can specify the units L#263

---

- [x] merge configuration options PR

### https://github.com/meilisearch/transplant/issues/188 `fieldsDistribution` renamed to `fieldDistribution`
- [x] reference/api/stats.md: rename `fieldsDistribution` to `fieldDistribution` L#27, L#57, L#68 #1056

### https://github.com/meilisearch/transplant/issues/138 `buildDate` renamed to `commitDate`
- [x] Fix in `/version` route
- [x] Fix in Updating MeiliSearch guide
- [x] PR created: #942
- [x] PR merged

## https://github.com/meilisearch/transplant/issues/17#issuecomment-865912189 Errors removed
- [x] `invalid_facet` removed
- [x] `missing_header` removed
- [x] `search_error` removed
- [x] `bad_parameter` removed
- [x] PR created: https://github.com/meilisearch/documentation/pull/1007
- [x] PR merged

### Update `.code-samples.meilisearch.yaml` in Curl, Golang, JavaScript, PHP, Python, Ruby, Rust, and Swift repos

1. `attributesForFaceting` changed to `filterableAttributes`
  - `faceted_search_update_settings_1`
  - `faceted_search_walkthrough_attributes_for_faceting_1` -> `faceted_search_walkthrough_filterable_attributes_1`
  - `get_attributes_for_faceting_1` -> `get_filterable_attributes_1`
  - `update_attributes_for_faceting_1` -> `update_filterable_attributes_1`
  - `reset_attributes_for_faceting_1` -> `reset_filterable_attributes_1`
2. `filters` changed to `filter`
  - `filtering_guide_1`, `filtering_guide_2`, `filtering_guide_3`, `filtering_guide_4`
  - `search_parameter_guide_filter_1`, `search_parameter_guide_filter_2`
  - `search_guide_2`
  - `search_parameter_guide_matches_1`--example changed
3. `facetFilters` changed to `filter`
  - `faceted_search_facet_filters_1` -> `faceted_search_filter_1`
  - `faceted_search_walkthrough_facet_filters_1` -> `faceted_search_walkthrough_filter_1`
4. `wordsPosition` removed and `words` switched with `typo`
  - `update_ranking_rules_1`
  - `settings_guide_ranking_rules_1`
  - `update_settings_1`

- Curl
  - [x] PR created https://github.com/meilisearch/documentation/pull/1025
  - [x] PR merged

- SDKs
  - [x] PRs created
  - [x] PRs merged

## Unsorted/unconfirmed
- [x] Update OpenAPI w/ changes to parameter + settings names

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Based on what has been talked about in this [javascript pr](https://github.com/meilisearch/meilisearch-js/pull/934):

### phrase search

It would be a great moment to add an example of [`phrase search`](https://github.com/meilisearch/documentation/pull/1021/files) since depending on the SDK the use of double quotes may impact the way we use `phrase search`. 

### Shifu examples

Shifu examples are really mediocre: 

highlight

Same for `matches`

It could be changed with the following example 

```
search_parameter_guide_highlight_1:
  client.index('movies').search('winter feast', {
    attributesToHighlight: ['overview']
  })
```

The results would then be: 

```
{
  "id": "50393",
  "title": "Kung Fu Panda Holiday",
  "poster": "https://image.tmdb.org/t/p/w1280/gp18R42TbSUlw9VnXFqyecm52lq.jpg",
  "overview": "The <em>Winter Feast</em> is Po's favorite holiday. Every year he and his father hang decorations, cook together, and serve noodle soup to the villagers. But this year Shifu informs Po that as Dragon Warrior, it is his duty to host the formal Winter Feast at the Jade Palace. Po is caught between his obligations as the Dragon Warrior and his family traditions: between Shifu and Mr. Ping.",
  "release_date": 1290729600
}
```

The same goes for [matches](https://docs.meilisearch.com/reference/features/search_parameters.html#matches)

By the way, the result of the matches example is wrong, as all SDK's have added `attributesToHighlight` but the return example does not have the highlighting.

## Updating ID`s 

ID`s should have the name related to the category, otherwise it confuses SDK's to what they have to implement and to where the code sample is put on the documentation. Plus, the consistency of course.

For example `faceted_search_facet_filters_1` should be renamed as `facet_filters` does not exist anymore.

## Updating code samples

This is not your work :) Based on this PR the integration team will update all SDK's

## Updating the template of code-samples

The template file [present here](https://github.com/meilisearch/documentation/blob/master/.vuepress/public/sample-template.yaml) should be updated with the new code sample ids.

**Comment by bidoubiwa** [comment]
Some routes will change names, for example `/reference/api/attributes_for_faceting.html`. It should be added in the redirect file.

I don't think it was written in the body of this PR, sorry if it is and I missed it.

**Comment by CaroFG** [comment]
Hi! I'm sorry if I missed it and it's already planned. According to the [What has changed with the v0.21.0 list](https://github.com/meilisearch/MeiliSearch/discussions/1519#discussioncomment-1030493), dumps do not rely anymore on displayedAttributes, so [the first step](https://github.com/meilisearch/documentation/blob/prepare-docs-v0.21/create/how_to/updating.md#step-1-set-all-fields-as-displayed-attributes) of the _Update to the latest MeiliSearch version_ (Updating from v0.15.0 or above) is no longer needed.

**Review by CaroFG — DISMISSED** [review]

**Review by curquiza — DISMISSED** [review]
Amazing and huge work! 🎉

**Review by gmourier — APPROVED** [review]
Sorry, I'm late @guimachiavelli! Thanks a lot! LGTM 🚀

**Review by guimachiavelli — APPROVED** [review]

**Review by gmourier — APPROVED** [review]
🚀

**Review by curquiza — APPROVED** [review]
💪

**Pull request merged**
