### PR TITLE
v0.28: API endpoint verbs update

### LINKED ISSUE #1702: v0.28: API endpoint verbs update
We are changing the verbs for some of our endpoints, mostly so we abide more faithfully to REST standards:

## Indexes API
- PUT -> PATCH /indexes/{indexUid}

## Settings API
- POST -> PATCH /indexes/{indexUid}/settings
- POST -> PATCH /indexes/{indexUid}/settings/typo-tolerance
- POST -> PUT /indexes/{indexUid}/settings/displayed-attributes
- POST -> PUT /indexes/{indexUid}/settings/distinct-attribute
- POST -> PUT /indexes/{indexUid}/settings/filterable-attributes
- POST -> PUT /indexes/{indexUid}/settings/ranking-rules
- POST -> PUT /indexes/{indexUid}/settings/searchable-attributes
- POST -> PUT /indexes/{indexUid}/settings/sortable-attributes
- POST -> PUT /indexes/{indexUid}/settings/stop-words
- POST -> PUT /indexes/{indexUid}/settings/synonyms

### References
Spec: https://github.com/meilisearch/specifications/pull/152
Issue on core: https://github.com/meilisearch/meilisearch/issues/2419
SME: @gmourier

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1702

### CODE REVIEW

**Review by guimachiavelli — COMMENTED** [review]
Is it me being blind or are we missing the verb update on the update an index endpoint?

I'm talking about this one:

- PUT -> PATCH /indexes/{indexUid}

**Comment by maryamsulemani97** [comment]
Yes, it's missing. Thanks Gui!

**Comment by guimachiavelli** [comment]
Oops, found another missing update: code sample `geosearch_guide_filter_settings_1`

**Review by guimachiavelli — APPROVED** [review]
🏞️

**Pull request merged**
