### PR TITLE
update quick start code sample

### LINKED ISSUE #1758: Quick start code sample outdated
The cdn used in the [Front-end integration section](https://docs.meilisearch.com/learn/getting_started/quick_start.html#front-end-integration) specifies a really old version of instant-meilisearch, which leads to issues like: 

`MeiliSearchApiError: Json deserialize error: unknown field `facetFilters`

It would be preferable not to specify a version, like so: 
`    <script src="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.min.js"></script>`

### PR DESCRIPTION
**Pull request by maryamsulemani97**
closes #1758

### CODE REVIEW

**Comment by dichotommy** [comment]
Did you test this?

**Comment by maryamsulemani97** [comment]
Yes

**Review by dichotommy — APPROVED** [review]
LGTM! I see that this was already the case for the Vue and React samples.

**Comment by maryamsulemani97** [comment]
bors merge

**Pull request merged**
