### PR TITLE
v0.26: Replace search preview images

### LINKED ISSUE #1421: v0.26: Rebranded search preview
## Summary
Meilisearch revealed its new brand on January 2022. The search preview will receive a fresh coat of pain and a new logo, but should remain unchanged otherwise.

## Tasks
Update the following media files
- [ ] aws/enjoy.png
- [ ] movie-gifs/trumen.[jpg|gif|mp4|webm]
- [ ] search_preview.png
- [ ] search_preview_no_documents.png
- [ ] search-synonyms.png

@mdubus recently updated some of these if I'm not wrong, so whoever is in charge of this issue might want to check her workflow and replicate it for consistency's sake.

## References
Issue on core: https://github.com/meilisearch/meilisearch/issues/2119
Discussion thread: https://github.com/meilisearch/documentation/discussions/1365#discussioncomment-2059889

### PR DESCRIPTION
**Pull request by mdubus**
# Pull Request

## What does this PR do?
Fixes #1421

## Note
I didn't replace the `search-synonyms.png` because we don't see any logo on it, so no need for a change :) 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by dichotommy** [comment]
Hey @mdubus thanks so much for doing this 😄 

I notice that the cycle for `.vuepress/public/movie-gifs/trumen-fast.gif` appears to be longer than the previous version, is there any way you could trim the beginning and end of the gif so that it loops more quickly? 👀 ⚡

**Comment by guimachiavelli** [comment]
Oh, wow, thank you so much for this, @mdubus! Just made our lives a bit easier ❤️ 

I will let @dichotommy handle the review itself, but I wanted to confirm something: the rebranded interface will only be available on v0.26 and v0.25.x will continue with the old branding until the release, right?

**Comment by mdubus** [comment]
> Oh, wow, thank you so much for this, @mdubus! Just made our lives a bit easier ❤️
> 
> I will let @dichotommy handle the review itself, but I wanted to confirm something: the rebranded interface will only be available on v0.26 and v0.25.x will continue with the old branding until the release, right?

I think you're right ! 
Should I set an other target branch for merge ? We can also wait until the release of the v0.26 before merging it 🤷‍♀️

**Comment by guimachiavelli** [comment]
I have a meeting with core later today and will confirm it, just to be sure.

If that is indeed the case, I will create a staging branch for all v0.26 stuff and let you know so you can change the target branch.

**Comment by mdubus** [comment]
> I have confirmed that the new interface is part of v0.26 and will only be visible once the new version has been officially released.
> 
> @mdubus, could you change the target from master to #1437's branch, `v0.26`?

Done ! 
Thank you so much @guimachiavelli for the information ! 😊

**Review by dichotommy — APPROVED** [review]
@mdubus Thanks so much for helping out!

Achievement unlocked: **shooter of screens** 👾 🏆

**Comment by guimachiavelli** [comment]
bors merge

**Pull request merged**
